### PR TITLE
Fix for Issue 119.

### LINKED ISSUE #119: Sinatra::Namespace does not handle specific error correctly when namespace contains :params
Hi,

I am trying to upgrade to Sinatra version 1.4.4 and the following spec fails for me, which used to work. In the code below the "should not come here" error is raised, while I expected that the error should be captured by the namespace block as it was in Sinatra 1.3.6.

When the namespace is declared as ```namespace '/bar' do ... end ``` all works fine. When I use ```namespace '/bar/:id' do ... end ``` it breaks.

```ruby
class FooError < StandardError
end
class FooBase < Sinatra::Base
  register Sinatra::Namespace
  error do
    raise "should not come in here"
  end
end
class FooForSpec < FooBase

  namespace '/bar/:id' do |_|

    error FooError do
      halt 201
    end

    get '/?' do
      raise FooError
    end

  end
end

describe FooForSpec do
  it "captures the error in the namespace block" do
    get '/bar/1'
    status.should == 201
  end
end
```

### PR DESCRIPTION
**Pull request by lvonk**
Make sure error blocks with custom Exceptions are handled when namespace is declared as '/foo/:id'. fixes #119.

### CODE REVIEW

**Comment by zzak** [comment]
@lvonk Hey! Sorry I missed this, are you still having this issue?

Would you be willing to rebase your patch?

**Comment by TrevorBramble** [comment]
@lvonk Hi, Lars. @zzak and I just took another look at this. Could you clarify what isn't working correctly with Sinatra::Cookie for us?

**Comment by lvonk** [comment]
Hi, yes the issue is still present. After rebasing the patch the Sinatra::Cookie error is gone. It is too long ago to remember what exactly was wrong. Builds are all green now.

**Comment by zzak** [comment]
@lvonk Thanks! I will try our test, to see if it still fails.

In the mean time, can you address some comments I made on the patch?

File: lib/sinatra/namespace.rb [hunk 1]
```diff
@@ -187,9 +188,11 @@ def namespace_errors
       end
 
       def error(*codes, &block)
-        args  = Sinatra::Base.send(:compile!, "ERROR", /^#{@pattern}/, block)
-        codes = codes.map { |c| Array(c) }.flatten
+        args  = Sinatra::Base.send(:compile!, "ERROR", regexpify(@pattern), block)
```
Comment (zzak) [inline lib/sinatra/namespace.rb]: Let's wait on this refactor until we fix any (remaining) bugs here.

File: lib/sinatra/namespace.rb [hunk 2]
```diff
@@ -187,9 +188,11 @@ def namespace_errors
...
+        codes = codes.flat_map { |c| Array(c) }
```
Comment (zzak) [inline lib/sinatra/namespace.rb]: Can we still use `flat_map()` on 1.8?

File: sinatra-contrib.gemspec [hunk 3]
```diff
@@ -187,7 +187,7 @@ Gem::Specification.new do |s|
     "spec/streaming_spec.rb"
   ]
 
-  s.add_dependency "sinatra",   "~> 1.4.0"
+  s.add_dependency "sinatra",   "~> 1.4.4"
```
Comment (zzak) [inline sinatra-contrib.gemspec]: Please remove this change as well

File: spec/namespace_spec.rb [hunk 4]
```diff
@@ -14,7 +14,6 @@ def mock_app(&block)
   def namespace(*args, &block)
     mock_app { namespace(*args, &block) }
   end
-
```
Comment (zzak) [inline spec/namespace_spec.rb]: :scissors: not needed

File: lib/sinatra/namespace.rb [hunk 5]
```diff
@@ -176,6 +176,7 @@ def invoke_hook(name, *args)
 
       def not_found(&block)
         error(404, &block)
+        error(Sinatra::NotFound, &block)
```
Comment (zzak) [inline lib/sinatra/namespace.rb]: I think we should do one or the other, but not both.

File: lib/sinatra/namespace.rb (hunk 2 above)
Comment (lvonk) [inline lib/sinatra/namespace.rb]: What do you mean? Do you want to support ruby 1.8?

File: lib/sinatra/namespace.rb (hunk 1 above)
Comment (lvonk) [inline lib/sinatra/namespace.rb]: What refactor do you mean? The `regexpify(@pattern)` is the fix for the bug described.

File: lib/sinatra/namespace.rb (hunk 2 above)
Comment (zzak) [inline lib/sinatra/namespace.rb]: We still support Ruby 1.8.7

**Comment by zzak** [comment]
Can you squash your commits too please?

**Comment by lvonk** [comment]
Done. Thanks for all the feedback.

**Comment by TrevorBramble** [comment]
Thanks for your work, @lvonk!
